/**
 * All Action types will listed here
 */

//COMMON ACTIONS
export const UPDATE_PLAYER_ONE_NAME = 'UPDATE_PLAYER_ONE_NAME';
export const UPDATE_PLAYER_TWO_NAME = 'UPDATE_PLAYER_TWO_NAME';

export const UPDATE_PLAYER_ONE_WINS = 'UPDATE_PLAYER_ONE_WINS';
export const UPDATE_PLAYER_TWO_WINS = 'UPDATE_PLAYER_TWO_WINS';

